version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ape-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ape_db
      - ONEAPIIRS_SECRET_KEY=segredo_super_secreto
      - ONEAPIIRS_PUBLIC_KEY=   # pode deixar vazio se não usar
      - ONEAPIIRS_ALGORITHM=HS256
      - ONEAPIIRS_TOKEN_EXPIRE_MIN=30
      - DATABASE_NAME=ape_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DRIVER=postgresql
      - APP_ENV=development
      - DEBUG=True
      - TESTING=False
      - API_VERSION=v1
      - API_PREFIX=/api/v1
      - ENABLE_DOCS=True
    networks:
      - ape_network  

  db:
    image: postgres:14-alpine
    container_name: ape-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ape_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ape_network

volumes:
  postgres_data:


networks:
  ape_network:

